name: monex-server

version: '3.8'

services:
  server:
    container_name: monex-server
    image: yourdockerhub/monex-server:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
